apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coffee-db
    app.kubernetes.io/component: coffee-db
    app.kubernetes.io/instance: coffee-db
  name: coffee-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-db
  template:
    metadata:
      labels:
        app: coffee-db
    spec:
      containers:
      - name: postgresql
        env:
        - name: POSTGRESQL_USER
          value: dbuser
        - name: POSTGRESQL_PASSWORD
          value: dbpass
        - name: POSTGRESQL_DATABASE
          value: db
        - name: POSTGRESQL_ADMIN_PASSWORD
          value: admin!
        image: registry.redhat.io/rhel8/postgresql-96:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: coffee-db-claim
      restartPolicy: Always
