apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: kaffeehaus
    name: openjdk16-openj9
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: adoptopenjdk/openjdk16-openj9:x86_64-alpine-jre-16.0.1_9_openj9-0.26.0
      from:
        kind: DockerImage
        name: adoptopenjdk/openjdk16-openj9:x86_64-alpine-jre-16.0.1_9_openj9-0.26.0
      generation: null
      importPolicy: {}
      name: x86_64-alpine-jre-16.0.1_9_openj9-0.26.0
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: kaffeehaus
    name: kaffeehaus
  spec:
    lookupPolicy:
      local: true
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: kaffeehaus
    name: kaffeehaus
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: kaffeehaus:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: main
        uri: https://github.com/sdaschner/kaffeehaus-demo
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: openjdk16-openj9:x86_64-alpine-jre-16.0.1_9_openj9-0.26.0
      type: Docker
    triggers:
    - github:
        secret: OWq9Zz88CZHtJKI09Cbk
      type: GitHub
    - generic:
        secret: xnG4n05zSbI79w6I_E9b
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
