kind: Deployment
apiVersion: apps/v1
metadata:
  name: kaffeehaus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaffeehaus
      version: v1
  template:
    metadata:
      labels:
        app: kaffeehaus
        version: v1
    spec:
      containers:
      - name: kaffeehaus
        image: sdaschner/kaffeehaus:quarkus-testing-1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      restartPolicy: Always
---

