kind: Route
apiVersion: v1
metadata:
  name: kaffeehaus
spec:
  #  host: kaffeehaus.openshift.example.com
  tls:
    termination: edge
  to:
    kind: Service
    name: kaffeehaus
    weight: 100
  wildcardPolicy: None
---